// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuIUPBUFs83qhTYNBd46Xh1gnB_vhAMvM',
    appId: '1:595354857469:web:ebbe82341ddbf699107394',
    messagingSenderId: '595354857469',
    projectId: 'watering-sekolah-santai-362ca',
    authDomain: 'watering-sekolah-santai-362ca.firebaseapp.com',
    storageBucket: 'watering-sekolah-santai-362ca.appspot.com',
    measurementId: 'G-QD39EGEQR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwiC-Tl0VgGwsK9e8hleijaM4A-1IhFZs',
    appId: '1:595354857469:android:8f7f53eab720dc2f107394',
    messagingSenderId: '595354857469',
    projectId: 'watering-sekolah-santai-362ca',
    storageBucket: 'watering-sekolah-santai-362ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1wLZtBCA6S1IguL3OPpZ1Jmo551Cu2s4',
    appId: '1:595354857469:ios:7e5ab2ffdc554224107394',
    messagingSenderId: '595354857469',
    projectId: 'watering-sekolah-santai-362ca',
    storageBucket: 'watering-sekolah-santai-362ca.appspot.com',
    iosClientId: '595354857469-9qnqdvn9h8laqvog0k47ovm0f82d44bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.wateringSekolah',
  );
}
